apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "assessment.fullname" . }}-backend
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "assessment.name" . }}
    component: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ include "assessment.name" . }}
      component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: {{ include "assessment.name" . }}
        component: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          ports:
            - containerPort: {{ .Values.backend.service.targetPort }}  # Use targetPort from values
          env:
            - name: DB_HOST
              value: "assessment-postgresql-ha-pgpool"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-ha-passwords
                  key: password
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}