{{- if .Values.internalIngress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-internal
  annotations:
    {{- if .Values.internalIngress.annotations }}
    {{ toYaml .Values.internalIngress.annotations | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.internalIngress.className }}
  rules:
    {{- range .Values.internalIngress.hosts }}
    - host: {{ .host | default "frontend.local" | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path | default "/api/internal" | quote }}
            pathType: {{ .pathType | default "ImplementationSpecific" | quote }}
            backend:
              service:
                name: {{ $.Release.Name }}-frontend
                port:
                  number: {{ $.Values.frontend.service.port | default 80 }}
          {{- end }}
    {{- end }}
{{- end }}